---
title: "Cincinnati, Ohio"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Cincinnati Riverfront
### Date: `r format(Sys.time(), '%d %B, %Y')`
```{r}
library(leaflet)
cinti <- leaflet() %>%
      addTiles() %>%
      setView(lat = 39.10713, lng = -84.50413, zoom = 13) %>%
      addMarkers(lng = c(-84.6630165, -84.50745, -84.51603, -84.50858, -84.53745,
                                -84.49712, -84.46381, -84.47632, -84.52058, -84.26808),
                 lat = c(39.0532746, 39.09761, 39.09541, 39.14454, 39.10963,
                                39.11366, 39.03122, 39.15017, 39.13031, 39.3432),
                 popup = c("Cincinnati/Northern Kentucky Airport",
                                  "Great American Ball Park (The Reds)",
                                  "Paul Brown Stadium (The Bengals)",
                                  "Cincinnati Zoo", "Cincinnati Museum Center",
                                  "Cincinnati Art Museum", "Northern Kentucky University",
                                  "Xavier University", "University of Cincinnati",
                                  "Paramount Kings Island"))
cinti
```



