---
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE, echo = FALSE, results = "markup", cache = FALSE)
```


`r format(Sys.time(), '%d %B, %Y')`
```{r cinti_leaflet_map, fig.align ='center', fig.height = 5, fig.width = 8}
library(leaflet)
cinti <- leaflet(width = "100%") %>%
      addTiles() %>%
      setView(lat = 39.10713, lng = -84.50413, zoom = 14) %>%
      addMarkers(lng = -84.50745, lat = 39.09761,
                label = "Great American Ball Park(Reds)",
                labelOptions = labelOptions(noHide = T, direction = "top",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px"))) %>%
     addMarkers(lng = -84.51603, lat = 39.09541,
                label = "Paul Brown Stadium(Bengals)",
                labelOptions = labelOptions(noHide = T, direction = "auto",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px"))) %>%
     addMarkers(lng = -84.50858, lat = 39.14454,
                label = "Cincinnati Zoo",
                labelOptions = labelOptions(noHide = T, direction = "top",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px"))) %>%
     addMarkers(lng = -84.512276, lat = 39.101596,
                label = "Fountain Square",
                labelOptions = labelOptions(noHide = T, direction = "top",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px"))) %>%
     addMarkers(lng = -84.53745, lat = 39.10963,
                label = "Cincinnati Museum Center",
                labelOptions = labelOptions(noHide = T, direction = "top",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px"))) %>%
     addMarkers(lng = -84.49712, lat = 39.11366,
                label = "Cincinnati Art Museum",
                labelOptions = labelOptions(noHide = T, direction = "top",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px"))) %>%
     addMarkers(lng = -84.47632, lat = 39.15017,
                label = "Xavier University(Musketeers)",
                labelOptions = labelOptions(noHide = T, direction = "top",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px"))) %>%
     addMarkers(lng = -84.52058, lat = 39.13031,
                label = "University of Cincinnati(Bearcats)",
                labelOptions = labelOptions(noHide = T, direction = "top",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px"))) %>%
     addMarkers(lng = -84.511239, lat = 39.097624,
                label = "National Underground Railroad Freedom Center",
                labelOptions = labelOptions(noHide = T, direction = "auto",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px"))) %>%
     addMarkers(lng = -84.518832, lat = 39.1153374,
                label = "Findlay Market",
                labelOptions = labelOptions(noHide = T, direction = "top",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px"))) %>%
     addMarkers(lng = -84.506488, lat = 39.103197,
                label = "Aranoff Center for the Arts",
                labelOptions = labelOptions(noHide = T, direction = "top",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px"))) %>%
     addMarkers(lng = -84.497842, lat = 39.111354,
                label = "Playhouse in the Park",
                labelOptions = labelOptions(noHide = T, direction = "top",
                                            style = list(
                                                "color" = "red",
                                                "font-style" = "italic",
                                                "font-size" = "11px")))
cinti
```





